version: '3.2'
services:
  aggregator:
    image: gentran1991/iotse-prototype:aggregator-rf
    environment:
      - WF_SERVER=conductor-server:8080
      - HOST_ADDR_PORT=http://aggregator:5000
      - REDIS_HOST=redis-cloud
      - REDIS_POST=6379
      - REDIS_DB=0
      - AGG_ADD_RESULT_TASK_NAME=add_result
      - AGG_AGGREGATE_TASK_NAME=aggregate
    ports:
      - 5001:5000
    deploy:
      placement:
        constraints: [node.hostname == cloud]
    networks:
      - iotse
      
  reading-searcher:
    image: gentran1991/iotse-prototype:reading-searcher-rf
    environment:
      - WF_SERVER=conductor-server:8080
      - HOST_ADDR_PORT=http://reading-searcher:5000
      - REDIS_HOST=redis-cloud
      - REDIS_POST=6379
      - REDIS_DB=0
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - STORAGE_TASK_NAME=store_reading
      - SEARCHER_TASK_NAME=search_reading
    ports:
      - 5002:5000
    deploy:
      placement:
        constraints: [node.hostname == cloud]
    networks:
      - iotse
      
  metadata-searcher:
    image: gentran1991/iotse-prototype:metadata-searcher-rf
    environment:
      - WF_SERVER=conductor-server:8080
      - HOST_ADDR_PORT=http://metadata-searcher:5000
      - REDIS_HOST=redis-cloud
      - REDIS_POST=6379
      - REDIS_DB=0
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - STORAGE_TASK_NAME=store_metadata
      - SEARCHER_TASK_NAME=search_metadata
    ports:
      - 5003:5000
    deploy:
      placement:
        constraints: [node.hostname == cloud]
    networks:
      - iotse
      
  facade:
    image: gentran1991/iotse-prototype:facade-rf
    environment:
      - WF_SERVER=conductor-server:8080
      - HOST_ADDR_PORT=http://facade:5000
      - REDIS_HOST=redis-cloud
      - REDIS_POST=6379
      - REDIS_DB=0
      - FACADE_TASK_NAME=get_aggregated_result
      - SEARCH_WORKFLOW_NAME=iotse_prototype_search_seq
    ports:
      - 5000:5000
    deploy:
      placement:
        constraints: [node.hostname == cloud]
    networks:
      - iotse
      
  redis-cloud:
    image: redis
    deploy:
      placement:
        constraints: [node.hostname == cloud]
    networks:
      - iotse
      
  mongo:
    image: mongo
    ports:
      - 27017:27017
    deploy:
      placement:
        constraints: [node.hostname == cloud]
    networks:
      - iotse
      
      
      
      
  metadata-collector:
    image: gentran1991/iotse-prototype:metadata-collector-rf
    environment:
      - WF_SERVER=conductor-server:8080
      - HOST_ADDR_PORT=http://metadata-collector:5000
      - REDIS_HOST=redis-edge
      - REDIS_POST=6379
      - REDIS_DB=0
      - COLLECTOR_TASK_NAME=collect_metadata
    ports:
      - 5004:5000
    deploy:
      placement:
        constraints: [node.hostname == edge]
    networks:
      - iotse
      
  reading-collector:
    image: gentran1991/iotse-prototype:reading-collector-rf
    environment:
      - WF_SERVER=conductor-server:8080
      - HOST_ADDR_PORT=http://reading-collector:5000
      - REDIS_HOST=redis-edge
      - REDIS_POST=6379
      - REDIS_DB=0
      - COLLECTOR_TASK_NAME=collect_reading
    ports:
      - 5005:5000
    deploy:
      placement:
        constraints: [node.hostname == edge]
    networks:
      - iotse
      
  source-detector:
    image: gentran1991/iotse-prototype:source-detector-rf
    environment:
      - WF_SERVER=conductor-server:8080
      - HOST_ADDR_PORT=http://source-detector:5000
      - REDIS_HOST=redis-edge
      - REDIS_POST=6379
      - REDIS_DB=0
      - WSP_HOST_PORT=http://wsp:8500/v1.0
      - DETECTOR_TASK_NAME=detect_source
    ports:
      - 5006:5000
    deploy:
      placement:
        constraints: [node.hostname == edge]
    networks:
      - iotse
      
  sensor-detector:
    image: gentran1991/iotse-prototype:sensor-detector-rf
    environment:
      - WF_SERVER=conductor-server:8080
      - HOST_ADDR_PORT=http://sensor-detector:5000
      - REDIS_HOST=redis-edge
      - REDIS_POST=6379
      - REDIS_DB=0
      - DETECTOR_TASK_NAME=detect_sensor
    ports:
      - 5007:5000
    deploy:
      placement:
        constraints: [node.hostname == edge]
    networks:
      - iotse
      
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - iotse
      
  redis-edge:
    image: redis
    deploy:
      placement:
        constraints: [node.hostname == edge]
    networks:
      - iotse
      
  wsp:
    image: gentran1991/wsp:wsp
    ports:
      - 8500:8500
    deploy:
      placement:
        constraints: [node.hostname == iot-gateway]
    networks:
      - iotse

networks:
  iotse:
    driver: overlay
    attachable: true
